<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributeProduct extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('attribute_products')->insert([

            [
                'id_product' => 1,
                'key' => 'Màu sắc',
                'value' => 'Ô liu nhạt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'key' => 'Kích cỡ',
                'value' => 'S, XS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'key' => 'Chất liệu',
                'value' => 'Nhôm cấp ALUXX, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'key' => 'Phuộc',
                'value' => 'thép cường độ cao, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'key' => 'Vành xe',
                'value' => 'Bộ bánh xe Giant GX Disc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'key' => 'Bàn đạp',
                'value' => 'nền tảng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'key' => 'Tay thắng',
                'value' => 'Tektro thủy lự',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'key' => 'Yên',
                'value' => 'Liv ErgoMax',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'key' => 'Cốt yên',
                'value' => 'Cầu chì D khổng lồ, hợp kim',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'key' => 'Màu sắc',
                'value' => 'xanh đen,gạch Bali',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'key' => 'Kích cỡ',
                'value' => 'S, XS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'key' => 'Chất liệu',
                'value' => 'Nhôm cấp ALUXX, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'key' => 'Phuộc',
                'value' => 'thép cường độ cao, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'key' => 'Vành xe',
                'value' => 'Bộ bánh xe Giant GX Disc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'key' => 'Bàn đạp',
                'value' => 'nền tảng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'key' => 'Tay thắng',
                'value' => 'Tektro cơ khí',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'key' => 'Yên xe',
                'value' => 'Yên xe Liv Sport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'key' => 'Cốt yên',
                'value' => 'Cầu chì D khổng lồ, hợp kim, 30,9mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'key' => 'Màu sắc',
                'value' => 'Xanh navy, Trắng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'key' => 'Kích cỡ',
                'value' => 'S, M, L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'key' => 'Chất liệu',
                'value' => 'Nhôm cấp ALUXX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'key' => 'Phuộc',
                'value' => 'SR Suntour NEX HLO 700C, 63mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'key' => 'Vành xe',
                'value' => 'Nhôm hai lớp khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'key' => 'Bàn đạp',
                'value' => 'nền tảng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'key' => 'Tay thắng',
                'value' => 'Tektro TKD-143',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'key' => 'Yên xe',
                'value' => 'Thể thao khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'key' => 'Cốt yên',
                'value' => 'Giant D-Fuse, hợp kim, 350mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'key' => 'Màu sắc',
                'value' => 'Đen, Bụi Sao Hỏa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'key' => 'Kích cỡ',
                'value' => 'S, M, L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'key' => 'Chất liệu',
                'value' => 'Nhôm cấp ALUXX, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'key' => 'Phuộc',
                'value' => 'SR Suntour NEX HLO 700C, 63mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'key' => 'Vành xe',
                'value' => 'Nhôm hai lớp khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'key' => 'Bàn đạp',
                'value' => 'nền tảng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'key' => 'Tay thắng',
                'value' => 'Tektro TKD-173',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'key' => 'Yên xe',
                'value' => 'ErgoLiên hệ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'key' => 'Cốt yên',
                'value' => 'Giant D-Fuse, hợp kim, 350mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'key' => 'Màu sắc',
                'value' => 'Đen, xanh dương,đỏ, trắng,xám mờ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'key' => 'Kích cỡ',
                'value' => 'S, M, L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'key' => 'Chất liệu',
                'value' => 'Nhôm cấp ALUXX, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'key' => 'Phuộc',
                'value' => 'SR Suntour 700C, 63mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'key' => 'Vành xe',
                'value' => 'cacbon hai lớp khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'key' => 'Bàn đạp',
                'value' => 'nền tảng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'key' => 'Tay thắng',
                'value' => 'TroTell TKD-173',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'key' => 'Yên xe',
                'value' => 'ErgoLiên hệ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'key' => 'Cốt yên',
                'value' => 'Giant D-Fuse, hợp kim',

                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 
            [
                'id_product' => 6,
                'key' => 'Màu sắc',
                'value' => 'Đen,trắng,xám',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'key' => 'Kích cỡ',
                'value' => 'One size (700C)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'key' => 'Chất liệu',
                'value' => 'Jeep Magie',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'key' => 'Phuộc',
                'value' => 'Jeep STL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'key' => 'Vành xe',
                'value' => 'ALU, Double Wall, 36H, Schrader valve',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'key' => 'Bàn đạp',
                'value' => 'Black PP Platform',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'key' => 'Tay đế',
                'value' => 'Jeep, 24 Speed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'key' => 'Yên xe',
                'value' => 'Jeep',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'key' => 'Cốt yên',
                'value' => '30.4x300mm STL',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 7,
                'key' => 'Màu sắc',
                'value' => 'Trắng,vàng đồng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'key' => 'Kích cỡ',
                'value' => 'XS, S, M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'key' => 'Chất liệu',
                'value' => 'Nhôm cấp ALUXX, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'key' => 'Phuộc',
                'value' => 'Tay lái OverDrive bằng vật liệu composite cấp cao, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'key' => 'Vành xe',
                'value' => 'Nhôm hai lớp khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'key' => 'Bàn đạp',
                'value' => 'Giant Urban Fitness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'key' => 'Tay đế',
                'value' => 'Shimano CUES U4000, 9 tốc độ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'key' => 'Yên xe',
                'value' => 'Giant ErgoContact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'key' => 'Cốt yên',
                'value' => 'Cầu chì D khổng lồ, hợp kim',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 8,
                'key' => 'Màu sắc',
                'value' => 'Đen, Trắng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'key' => 'Kích cỡ',
                'value' => 'One size (700C)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'key' => 'Chất liệu',
                'value' => 'Jeep ALU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'key' => 'Phuộc',
                'value' => 'Jeep STL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'key' => 'Vành xe',
                'value' => 'ALU, Double Wall, 36H, Schrader valve',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'key' => 'Bàn đạp',
                'value' => 'Black PP Platform',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'key' => 'Tay đế',
                'value' => 'Jeep, 24 Speed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'key' => 'Yên xe',
                'value' => 'Jeep',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'key' => 'Cốt yên',
                'value' => '30.4x300mm STL',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 9,
                'key' => 'Màu sắc',
                'value' => 'Đen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'key' => 'Kích cỡ',
                'value' => 'XS, S, M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'key' => 'Chất liệu',
                'value' => 'Composite cấp cao, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'key' => 'Phuộc',
                'value' => 'Composite cấp cao, tay lái OverDrive hợp kim, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'key' => 'Vành xe',
                'value' => 'Bộ bánh xe Giant P-R2 Disc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'key' => 'Giò dĩa',
                'value' => 'Omega 48/32T',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'key' => 'Tay đế',
                'value' => 'Shimano 105 SL-RS700, 2×11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'key' => 'Yên xe',
                'value' => 'Giant ErgoContact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'key' => 'Cốt yên',
                'value' => 'Cầu chì D khổng lồ, composite',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 10,
                'key' => 'Màu sắc',
                'value' => 'xám',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'key' => 'Kích cỡ',
                'value' => 'XS, S',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'key' => 'Chất liệu',
                'value' => 'Nhôm ALUXX-Grade, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'key' => 'Phuộc',
                'value' => 'Hợp kim, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'key' => 'Vành xe',
                'value' => 'Nhôm hai lớp khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'key' => 'Giò dĩa',
                'value' => 'Nền tảng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'key' => 'Tay đế',
                'value' => 'Shimano Tourney 2×7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'key' => 'Yên xe',
                'value' => 'Sự thoải mái của Liv Sport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'key' => 'Cốt yên',
                'value' => 'Hợp kim D-Fuse khổng lồ',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 11,
                'key' => 'Màu sắc',
                'value' => 'xám',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'key' => 'Kích cỡ',
                'value' => 'XS, S',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'key' => 'Chất liệu',
                'value' => 'Nhôm ALUXX-Grade, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'key' => 'Phuộc',
                'value' => 'Hợp kim, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'key' => 'Vành xe',
                'value' => 'Nhôm hai lớp khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'key' => 'Giò dĩa',
                'value' => 'Bánh xe Prowheel, 30/48T',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'key' => 'Tay đế',
                'value' => 'Shimano Tourney 2×7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'key' => 'Yên xe',
                'value' => 'Sự thoải mái của Liv Sport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'key' => 'Cốt yên',
                'value' => 'Hợp kim D-Fuse khổng lồ',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 12,
                'key' => 'Màu sắc',
                'value' => 'than',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'key' => 'Kích cỡ',
                'value' => 'S, M, ML',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'key' => 'Chất liệu',
                'value' => 'Nhôm ALUXX-Grade, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'key' => 'Phuộc',
                'value' => 'Composite cấp cao',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'key' => 'Ghi đông',
                'value' => 'Hợp kim nhôm khổng lồ 31.8mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'key' => 'Giò dĩa',
                'value' => 'Omega 48/32T',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'key' => 'Tay đế',
                'value' => 'Shimano Sora 2×9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'key' => 'Yên xe',
                'value' => 'Giant EgroLiên hệ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'key' => 'Cốt yên',
                'value' => ' Hợp kim khổng lồ',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 13,
                'key' => 'Màu sắc',
                'value' => 'Helios màu cam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'key' => 'Kích cỡ',
                'value' => 'S, M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'key' => 'Chất liệu',
                'value' => 'Composite cấp cao, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'key' => 'Phuộc',
                'value' => 'Composite cấp cao, tay lái OverDrive hợp kim, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'key' => 'Ghi đông',
                'value' => 'Giant Connect, phẳng (XS: 58cm, S: 58cm, M: 58cm, M/L: 62cm, L: 62cm, XL: 62cm)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'key' => 'Giò dĩa',
                'value' => 'Omega 48/32T',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'key' => 'Tay đế',
                'value' => 'Shimano Tiagra SL-4700, 2×10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'key' => 'Yên xe',
                'value' => 'Giant EgroLiên hệ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'key' => 'Cốt yên',
                'value' => 'Cầu chì D khổng lồ',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 14,
                'key' => 'Màu sắc',
                'value' => 'Trắng, Xám',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'key' => 'Kích cỡ',
                'value' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'key' => 'Chất liệu',
                'value' => 'Hợp kim Magie',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'key' => 'Phuộc',
                'value' => 'Phuộc điều khiển Totem Pro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'key' => 'Ghi đông',
                'value' => 'Xe đạp leo núi Totem',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'key' => 'Giò dĩa',
                'value' => '28/38/48',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'key' => 'Tay đế',
                'value' => 'Shimano SL-M315 3×8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'key' => 'Yên xe',
                'value' => 'Núi Totem',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'key' => 'Cốt yên',
                'value' => 'Vật tổ',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 15,
                'key' => 'Màu sắc',
                'value' => 'Bạc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'key' => 'Kích cỡ',
                'value' => 'S,M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'key' => 'Chất liệu',
                'value' => 'Nhôm cấp ALUXX, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'key' => 'Phuộc',
                'value' => 'SR Suntour XCE, QR, tay lái bằng thép',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'key' => 'Ghi đông',
                'value' => 'Đường mòn Giant Connect, 31,8mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'key' => 'Giò dĩa',
                'value' => 'Shimano Altus FC-M315, 22/36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'key' => 'Tay đế',
                'value' => 'Shimano Altus, 2×8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'key' => 'Yên xe',
                'value' => 'Đường mòn ErgoContact khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'key' => 'Cốt yên',
                'value' => 'Thể thao khổng lồ, 30,9',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 16,
                'key' => 'Màu sắc',
                'value' => 'Đen bóng, Latte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'key' => 'Kích cỡ',
                'value' => 'Một kích thước (24")',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'key' => 'Chất liệu',
                'value' => 'Khung nhôm GIANT Youth 24”X12”',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'key' => 'Phuộc',
                'value' => 'Phuộc treo bằng thép cacbon cao 1-1/8” ống thẳng, hành trình treo 40MM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'key' => 'Ghi đông',
                'value' => 'Đường kính tâm nhôm 25,4mm Chiều dài 560mm Nâng 20mm Nghiêng về phía sau 10°',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'key' => 'Giò dĩa',
                'value' => '42/34/24 Bánh răng lớn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'key' => 'Tay đế',
                'value' => 'GIẢI ĐẤU SHIMANO 3X7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'key' => 'Yên xe',
                'value' => 'Yên xe cho thanh thiếu niên',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'key' => 'Cốt yên',
                'value' => 'Nhôm 30.9mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 17,
                'key' => 'Màu sắc',
                'value' => 'Xanh/Carbon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'key' => 'Kích cỡ',
                'value' => 'S',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'key' => 'Chất liệu',
                'value' => 'Composite cấp cao, trục xuyên 12x148mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'key' => 'Phuộc',
                'value' => 'RockShox SID SL, 100mm, độ lệch 44mm, Boost 15x110mm Maxle Stealth, tay lái thuôn nhọn, khóa từ xa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'key' => 'Ghi đông',
                'value' => 'Giant Contact SL XC, 780×31.8mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'key' => 'Giò dĩa',
                'value' => 'TruVativ Descendent 6k, Đại bàng, 32T',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'key' => 'Tay đế',
                'value' => 'SRAM NX Eagle, 1×12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'key' => 'Yên xe',
                'value' => 'Fizi:k Antares R7 với thanh ray hợp kim S',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'key' => 'Cốt yên',
                'value' => 'tổng hợp, 30,9x400mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 18,
                'key' => 'Màu sắc',
                'value' => 'Đen/Xám, Xám/Đỏ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'key' => 'Kích cỡ',
                'value' => 'S, M, L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'key' => 'Chất liệu',
                'value' => 'Composite cấp cao',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'key' => 'Phuộc',
                'value' => 'Giant Crest 34 RRL 27,5″',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'key' => 'Ghi đông',
                'value' => 'Giant Connect TR 31.8mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'key' => 'Giò dĩa',
                'value' => 'Bánh xe Prowheel 26/36T',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'key' => 'Tay đế',
                'value' => 'Shimano SLX 2×11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'key' => 'Yên xe',
                'value' => 'Thể thao khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'key' => 'Cốt yên',
                'value' => 'Hợp kim',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 19,
                'key' => 'Màu sắc',
                'value' => 'Đen, Sapphire',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'key' => 'Kích cỡ',
                'value' => 'S, M, L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'key' => 'Chất liệu',
                'value' => 'Nhôm ALUXX-Grade, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'key' => 'Phuộc',
                'value' => 'SR Suntour NEX HLO 700C, 63mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'key' => 'Ghi đông',
                'value' => 'Giant Sport XC, 31,8mm (S:640mm, M:680mm, L:680mm, XL:680mm)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'key' => 'Giò dĩa',
                'value' => 'Hợp kim rèn, 28/38/48 (S:170mm, M:170mm, L:175mm, XL:175mm)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'key' => 'Tay đế',
                'value' => 'Shimano Altus, 3×7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'key' => 'Yên xe',
                'value' => 'Thể thao khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'key' => 'Cốt yên',
                'value' => 'Giant D-Fuse, hợp kim, 350mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 20,
                'key' => 'Màu sắc',
                'value' => 'Đen/Vỏ trắng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'key' => 'Kích cỡ',
                'value' => 'S, M, L, XL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'key' => 'Chất liệu',
                'value' => 'Composite cấp cao, trục xuyên 12x148mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'key' => 'Phuộc',
                'value' => 'RockShox Recon Silver RL, 100mm, độ lệch 42mm, Boost 15x110mm Maxle Stealth, tay lái thuôn nhọn, khóa từ xa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'key' => 'Ghi đông',
                'value' => 'Giant Contact SL XC, 780×31.8mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'key' => 'Giò dĩa',
                'value' => 'Shimano SLX, 32T',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'key' => 'Tay đế',
                'value' => 'Shimano SLX SL-M7100, 1×12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'key' => 'Yên xe',
                'value' => 'Fizi:k Antares R7 với thanh ray hợp kim S',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'key' => 'Cốt yên',
                'value' => 'Kết nối khổng lồ, 30,9x400mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 21,
                'key' => 'Màu sắc',
                'value' => 'Kim cương đen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'key' => 'Kích cỡ',
                'value' => 'XS, S, M, M/L, L, XL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'key' => 'Chất liệu',
                'value' => 'Composite SL-Grade tiên tiến, cốt yên tích hợp, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'key' => 'Phuộc',
                'value' => 'Hệ thống lái OverDrive 2 bằng composite SL-Grade tiên tiến, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'key' => 'Ghi đông',
                'value' => 'Giant Contact SLR Aero (XS:40cm, S:40cm, M:42cm, M/L:42cm, L:44cm, XL:44cm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'key' => 'Giò dĩa',
                'value' => 'SRAM Force D1 DUB, 35/48 với đồng hồ đo công suất Quarq DZero (XS:170mm, S:170mm, M:172,5mm, M/L:172,5mm, L:175mm, XL:175mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'key' => 'Tay đế',
                'value' => 'SRAM Force eTap AXS 2×12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'key' => 'Yên xe',
                'value' => 'SLR hạm đội khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'key' => 'Cốt yên',
                'value' => 'Composite SL-Grade tiên tiến, thiết kế tích hợp, độ lệch -5/+15mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 22,
                'key' => 'Màu sắc',
                'value' => 'xanh,trắng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'key' => 'Kích cỡ',
                'value' => 'XS, S',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'key' => 'Chất liệu',
                'value' => 'Composite cấp cao, trục xuyên 12x142mm, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'key' => 'Phuộc',
                'value' => 'Hệ thống lái OverDrive Aero bằng vật liệu composite cấp cao, toàn bộ bằng vật liệu composite, trục xuyên tâm 12x100mm, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'key' => 'Ghi đông',
                'value' => 'Giant Contact SL Aero',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'key' => 'Giò dĩa',
                'value' => 'Shimano 105 Di2, 36/52',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'key' => 'Tay đế',
                'value' => 'SRAM Force eTap AXS 2×12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'key' => 'Trọng lượng',
                'value' => 'trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệuTr hoTrọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'key' => 'Yên xe',
                'value' => 'SLR hạm đội khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'key' => 'Cốt yên',
                'value' => 'Composite SL-Grade tiên tiến, thiết kế tích hợp, độ lệch -5/+15mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 23,
                'key' => 'Màu sắc',
                'value' => 'Nâu đất',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'key' => 'Kích cỡ',
                'value' => 'XS, S',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'key' => 'Chất liệu',
                'value' => 'Composite cấp cao, trục xuyên 12x142mm, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'key' => 'Phuộc',
                'value' => 'Tay lái OverDrive Aero bằng vật liệu composite cao cấp, hoàn toàn bằng vật liệu composite, 12x100mm, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'key' => 'Ghi đông',
                'value' => 'Liv Contact SL Aero, 31,8mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'key' => 'Giò dĩa',
                'value' => 'Shimano 105, 36/52 với đồng hồ đo công suất Giant Power Pro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'key' => 'Tay đế',
                'value' => 'Shimano 105 Di2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'key' => 'Yên xe',
                'value' => 'Cuộc sống Alcara SL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'key' => 'Cốt yên',
                'value' => 'Vector khổng lồ, tổng hợp',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 24,
                'key' => 'Màu sắc',
                'value' => 'Xanh kim loại Carbon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'key' => 'Kích cỡ',
                'value' => 'S, XS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'key' => 'Chất liệu',
                'value' => 'Composite cao cấp, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'key' => 'Phuộc',
                'value' => 'Tay lái OverDrive Aero hoàn toàn bằng composite SL-grade tiên tiến, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'key' => 'Ghi đông',
                'value' => 'Giant Contact SLR Aero',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'key' => 'Giò dĩa',
                'value' => 'Shimano Ultegra, 36/52, với đồng hồ đo công suất Giant Power Pro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'key' => 'Tay đế',
                'value' => 'Shimano Ultegra Di2 ST-R8170 2×1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'key' => 'Yên xe',
                'value' => 'Hạm đội khổng lồ SL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'key' => 'Cốt yên',
                'value' => 'Giant Vector, composite, bù trừ -5/+15mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 25,
                'key' => 'Màu sắc',
                'value' => 'Tím ánh kim,Carbon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'key' => 'Kích cỡ',
                'value' => 'S, XS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'key' => 'Chất liệu',
                'value' => 'Composite cao cấp, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'key' => 'Phuộc',
                'value' => 'Ống lái OverDrive 2 bằng vật liệu composite cao cấp, toàn bộ bằng vật liệu composite, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'key' => 'Ghi đông',
                'value' => 'Máy ảnh SLR liên lạc khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'key' => 'Giò dĩa',
                'value' => 'Shimano Ultegra, 36/52 với đồng hồ đo công suất Giant Power Pro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'key' => 'Tay đế',
                'value' => 'Shimano Ultegra Di2 ST-R8170',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'key' => 'Yên xe',
                'value' => 'Hạm đội khổng lồ SL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'key' => 'Cốt yên',
                'value' => 'Biến thể khổng lồ, composite, độ lệch -5/+15mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 26,
                'key' => 'Màu sắc',
                'value' => 'Đen kim loại, Trắng kỳ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'key' => 'Kích cỡ',
                'value' => 'S, M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'key' => 'Chất liệu',
                'value' => 'Nhôm cấp ALUXX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'key' => 'Phuộc',
                'value' => 'Tay lái OverDrive bằng vật liệu composite cao cấp, composite hoàn toàn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'key' => 'Ghi đông',
                'value' => 'Kết nối khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'key' => 'Giò dĩa',
                'value' => 'Shimano Sora, 34/50',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'key' => 'Tay đế',
                'value' => 'Shimano Sora',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'key' => 'Yên xe',
                'value' => 'Cách tiếp cận khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'key' => 'Cốt yên',
                'value' => 'Giant D-Fuse, hợp kim, độ lệch 14mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 27,
                'key' => 'Màu sắc',
                'value' => 'Xanh mạ non',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'key' => 'Kích cỡ',
                'value' => 'M, S, XS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'key' => 'Chất liệu',
                'value' => 'Nhôm cấp ALUXX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'key' => 'Phuộc',
                'value' => 'Phuộc đĩa nhôm ALUXX-Grade',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'key' => 'Ghi đông',
                'value' => 'Thể thao khổng lồ, 31,8mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'key' => 'Giò dĩa',
                'value' => 'Shimano FC-TY501, 30/46T',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'key' => 'Tay đế',
                'value' => 'Shimano SL-M315 2×8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'key' => 'Yên xe',
                'value' => 'Sự thoải mái của Liv Sport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'key' => 'Cốt yên',
                'value' => 'Thể thao khổng lồ, 27,2mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 28,
                'key' => 'Màu sắc',
                'value' => 'Màu hạt dẻ,xanh đọt chuối',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'key' => 'Kích cỡ',
                'value' => 'XS, S, M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'key' => 'Chất liệu',
                'value' => 'Nhôm ALUXX-Grade, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'key' => 'Phuộc',
                'value' => 'Hợp kim, đĩa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'key' => 'Ghi đông',
                'value' => 'Xe đạp thể thao Giant XC, 25,4mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'key' => 'Giò dĩa',
                'value' => 'Prowheel, 28/38/48',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'key' => 'Tay đế',
                'value' => 'Shimano Tourney 3×7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'key' => 'Yên xe',
                'value' => 'Sự thoải mái của Liv Sport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'key' => 'Cốt yên',
                'value' => 'Hợp kim D-Fuse khổng lồ',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 29,
                'key' => 'Màu sắc',
                'value' => 'Hồng/Trắng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'key' => 'Kích cỡ',
                'value' => 'Một kích thước (18″)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'key' => 'Chất liệu',
                'value' => 'TrinX STL 18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'key' => 'Phuộc',
                'value' => 'TrinXSTL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'key' => 'Ghi đông',
                'value' => '22,2x480mm STL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'key' => 'Giò dĩa',
                'value' => '28Tx130mm STL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'key' => 'Tay đế',
                'value' => 'Shimano Tourney 3×7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'key' => 'Yên xe',
                'value' => 'TrinX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'key' => 'Cốt yên',
                'value' => '25,4x200mm STL',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 30,
                'key' => 'Màu sắc',
                'value' => 'Xanh kim loại, Đen kim loại, Trắng ngọc trai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'key' => 'Kích cỡ',
                'value' => 'Một kích thước (20″)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'key' => 'Chất liệu',
                'value' => 'Khung gấp hợp kim nhôm GIANT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'key' => 'Phuộc',
                'value' => 'Thép chịu lực cao',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'key' => 'Ghi đông',
                'value' => 'Hợp kim nhôm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'key' => 'Giò dĩa',
                'value' => 'PRO-552 52T',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'key' => 'Tay đế',
                'value' => 'Shimano Revoshift 6 tốc độ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'key' => 'Trọng lượng',
                'value' => 'Trọng lượng có thể thay đổi dựa trên kích cỡ, chất liệu hoàn thiện, chi tiết kim loại và các phụ kiện.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'key' => 'Yên xe',
                'value' => 'Yên khổng lồ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'key' => 'Cốt yên',
                'value' => 'Hợp kim nhôm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 31,
                'key' => 'Chất Liệu	',
                'value' => 'Nhựa PP',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 31,
                'key' => 'Xuất xứ',
                'value' => 'Đài Loan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 31,
                'key' => 'Thông tin khác',
                'value' => 'Chống tia UV ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 31,
                'key' => 'Vành bánh xe',
                'value' => 'Phù hợp bánh 27.5″ đến 29″ ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 31,
                'key' => 'Ghi đông',
                'value' => 'tăng độ bền Có góc điều chỉnh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 32,
                'key' => 'Chất Liệu	',
                'value' => 'Nhựa ACP',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 32,
                'key' => 'Màu sắc',
                'value' => 'Đen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 32,
                'key' => 'Thông tin khác',
                'value' => 'Chống tia UV ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 33,
                'key' => 'Xuất xứ',
                'value' => 'Trung Quốc',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 33,
                'key' => 'Chất Liệu	',
                'value' => 'Nhựa tổng hợp + dây silicon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 33,
                'key' => 'Chế độ sáng',
                'value' => 'Sáng 100% – Sáng 50% – Nhấp nháy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 33,
                'key' => 'Pin',
                'value' => 'Trước: 2 x AA Sau: 1 x AA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 34,
                'key' => 'Chất Liệu',
                'value' => 'Hộp kim nhôm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 34,
                'key' => 'Xuất xứ',
                'value' => 'Đài Loan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 34,
                'key' => 'Thông tin khác',
                'value' => 'Tương thích với đầu bơm Control Blast Hộp đệm xốp có cách nhiệt mỏng Nhỏ tiết kiệm không gian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 34,
                'key' => 'Trọng lượng',
                'value' => '160g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 35,
                'key' => 'Chất Liệu',
                'value' => 'Sợi Carbon 3K',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 35,
                'key' => 'Xuất xứ',
                'value' => 'Đài Loan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 35,
                'key' => 'Thông tin khác',
                'value' => 'Dễ dàng tháo lắp Phù hợp với bình 500 – 750ml',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 35,
                'key' => 'Trọng lượng',
                'value' => '24g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //
            [
                'id_product' => 36,
                'key' => 'Chất Liệu',
                'value' => 'Nhựa tổng hợp',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 36,
                'key' => 'Màu sắc',
                'value' => 'Đen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 36,
                'key' => 'Xuất xứ',
                'value' => 'Trung Quốc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 36,
                'key' => 'Phù hợp với',
                'value' => 'Recon TL 200 và Recon TL 100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 37,
                'key' => 'Kích thước',
                'value' => '10×1000 mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 37,
                'key' => 'Chất liệu',
                'value' => 'Silicon bọc thép',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 37,
                'key' => 'Xuất xứ',
                'value' => 'Trung Quốc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 37,
                'key' => 'Trọng lượng',
                'value' => '400g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 38,
                'key' => 'Kích thước',
                'value' => '10×1000 mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 38,
                'key' => 'Chất liệu',
                'value' => 'Silicon bọc thép',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 38,
                'key' => 'Xuất xứ',
                'value' => 'Trung Quốc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 38,
                'key' => 'Trọng lượng',
                'value' => '460g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 39,
                'key' => 'Chất liệu',
                'value' => 'Steel',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 39,
                'key' => 'Mắc xích',
                'value' => '116L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 39,
                'key' => 'Xuất xứ',
                'value' => 'Nhật Bản',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 39,
                'key' => 'Tốc độ',
                'value' => '11 speed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 39,
                'key' => 'Liên kết',
                'value' => 'Master link (Quick-Link)',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 39,
                'key' => 'Công nghệ',
                'value' => 'HG-X11, SIL-TEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 39,
                'key' => 'Thông tin khác',
                'value' => 'Hiệu suất chuyển số mượt mà và đáng tin cậy Hiệu quả hơn và im lặng hơn, ít bảo trì hơn nhờ bề mặt được xử lý bằng công nghệ SIL-TEC trên tấm ngoài, tấm trong, con lăn Tương thích với hệ thống truyền động 11 tốc độ Chốt rỗng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 40,
                'key' => 'Chất liệu',
                'value' => 'Steel',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 40,
                'key' => 'Xuất xứ',
                'value' => 'Nhật Bản',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 40,
                'key' => 'Mắc xích',
                'value' => '126L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 40,
                'key' => 'Tốc độ',
                'value' => '9/10/11 speed',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 40,
                'key' => 'Liên kết',
                'value' => 'Master link (Quick-Link)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 40,
                'key' => 'Công nghệ',
                'value' => 'LINKGLIDE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 40,
                'key' => 'Thông tin khác',
                'value' => 'LINKGLIDEHiệu suất chuyển số mượt mà và đáng tin cậy Tương thích với hệ thống truyền động HYPEGLIDE 10/11 tốc độ và 11 tốc độ LINKGLIDE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 41,
                'key' => 'Chất liệu',
                'value' => 'Body: aluminium Axle : steel (CrMo)',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'key' => 'Xuất xứ',
                'value' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'key' => 'Loại',
                'value' => 'Clipless pedals',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'key' => 'Pedal',
                'value' => 'SPD',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'key' => 'Cleat Mount',
                'value' => '2-bolt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'key' => 'Stack height (mm)',
                'value' => '16.5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'key' => 'Thông tin khác',
                'value' => 'Bề mặt tiếp xúc với đế giày rộng hơn từ cạnh này sang cạnh kia để truyền lực tối ưu Chiều cao bệ thấp hơn để ổn định khi đạp Cơ chế liên kết hai mặt Tùy chỉnh cài đặt độ căng vào và ra Trục xoay mạ crôm mạnh mẽ, bền bỉ với giá đỡ cờ lê lục giác 8 mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 42,
                'key' => 'Chất liệu',
                'value' => 'Body: aluminium Axle : steel (CrMo)',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'key' => 'Xuất xứ',
                'value' => 'Malaysia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'key' => 'Loại',
                'value' => 'hybrid pedals (one side clipless, one side platform)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'key' => 'Pedal',
                'value' => 'SPD',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'key' => 'Cleat Mount',
                'value' => '2-bolt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'key' => 'Stack height (mm)',
                'value' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'key' => 'Thông tin khác',
                'value' => 'Bàn đạp đế ở một bên và bàn đạp SPD ở bên kia Cài đặt độ căng có thể điều chỉnh Độ bám được cải thiện: Mặt đế bao gồm khe hở kẹp lõm và chốt có độ bám cao Vòng bi cốc và hình nón kín giúp bảo dưỡng dễ dàng',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 43,
                'key' => 'Rim Material',
                'value' => 'Carbon',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 43,
                'key' => 'Loại vành',
                'value' => 'Móc khóa không có móc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 43,
                'key' => 'Không săm',
                'value' => 'Hệ thống không săm Giant (bao gồm băng vành và bộ van)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 43,
                'key' => 'Chiều cao vành	',
                'value' => '65mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 43,
                'key' => 'Chiều rộng vành ngoài	',
                'value' => '26mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 43,
                'key' => 'Trung tâm',
                'value' => 'Đùm ma sát thấp khổng lồ, Trình điều khiển bánh cóc 30T, Khóa trung tâm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 43,
                'key' => 'Khả năng tương thích của Hub	',
                'value' => 'Shimano HG, SRAM XDR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 44,
                'key' => 'Vật liệu vành',
                'value' => 'Carbon',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 44,
                'key' => 'Loại vành',
                'value' => 'Móc khóa không có móc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 44,
                'key' => 'Không săm',
                'value' => 'Hệ thống không săm Giant (bao gồm băng vành và bộ van)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 44,
                'key' => 'Chiều cao vành	',
                'value' => '42mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 44,
                'key' => 'Chiều rộng vành ngoài	',
                'value' => '26mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 44,
                'key' => 'Trung tâm',
                'value' => 'Hub ma sát thấp khổng lồ, Centerlock',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 44,
                'key' => 'Khả năng tương thích của Hub	',
                'value' => 'Shimano HG, SRAM XDR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 45,
                'key' => 'Kích thước',
                'value' => '700x35C',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 45,
                'key' => 'Chất Liệu',
                'value' => 'Cao su',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 45,
                'key' => 'Xuất xứ',
                'value' => 'Đài Loan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 45,
                'key' => 'Hợp chất',
                'value' => 'All-Terrain',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 45,
                'key' => 'Thông tin khác',
                'value' => '60TPI Sử dụng công nghệ EasyRide Tubeless',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 45,
                'key' => 'Trọng lượng',
                'value' => '772g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 45,
                'key' => 'Khả năng tương thích của Hub	',
                'value' => 'Shimano HG, SRAM XDR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 46,
                'key' => 'Kích thước',
                'value' => '27.5×2.10-2.40 Van Schrader 40mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 46,
                'key' => 'Chất Liệu',
                'value' => 'Cao su',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 46,
                'key' => 'Xuất xứ',
                'value' => 'Đài Loan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 47,
                'key' => 'Kích thước',
                'value' => 'Width: 400 mm Reach: 72 mm Drop: 125 mm Bar Clamp Diameter: 31.8 mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 47,
                'key' => 'Chất Liệu',
                'value' => 'Advanced SL Composite',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 47,
                'key' => 'Xuất xứ',
                'value' => 'Đài Loan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 47,
                'key' => 'Dòng xe phù hợp',
                'value' => 'Road',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 48,
                'key' => 'Kích thước',
                'value' => '10°x100mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 48,
                'key' => 'Chất Liệu',
                'value' => 'Advanced SL Composite',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 48,
                'key' => 'Xuất xứ',
                'value' => 'Đài Loan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 48,
                'key' => 'Dòng xe phù hợp',
                'value' => 'My23 Propel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 48,
                'key' => 'Trọng lượng',
                'value' => '143g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 49,
                'key' => 'Kích thước',
                'value' => '10°x100mm',

                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 49,
                'key' => 'Chất Liệu',
                'value' => 'Advanced SL Carbon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 49,
                'key' => 'Xuất xứ',
                'value' => 'Đài Loan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 49,
                'key' => 'Dòng xe phù hợp',
                'value' => 'My23 Propel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 49,
                'key' => 'Trọng lượng',
                'value' => '143g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 50,
                'key' => 'Chất Liệu',
                'value' => 'Steel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 50,
                'key' => 'Nhật Bản',
                'value' => 'Đài Loan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 50,
                'key' => 'Mắc xích',
                'value' => '126L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 50,
                'key' => 'Trọng lượng',
                'value' => '281g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 50,
                'key' => 'Thông tin khác',
                'value' => 'Hiệu suất chuyển số mượt mà và đáng tin cậy Lái xe mượt mà hơn ngay cả trên địa hình gập ghềnh Hiệu quả hơn và im lặng hơn, ít bảo trì hơn nhờ bề mặt được xử lý bằng công nghệ SIL-TEC Tương thích với hệ thống truyền động 12 tốc độ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'id_product' => 51,
                'key' => 'Chất Liệu',
                'value' => 'Steel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 51,
                'key' => 'Nhật Bản',
                'value' => 'Đài Loan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 51,
                'key' => 'Mắc xích',
                'value' => '116L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 51,
                'key' => 'Trọng lượng',
                'value' => '12 speed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 51,
                'key' => 'Thông tin khác',
                'value' => 'Hiệu suất chuyển số mượt mà và đáng tin cậy Lái xe mượt mà hơn ngay cả trên địa hình gập ghềnh Khả năng giữ xích tốt hơn để mở rộng phần ở cuối tấm bên trong nhằm giữ chắc răng cả phía trước và bánh xích cassette Hiệu quả hơn và im lặng hơn, ít bảo trì hơn nhờ bề mặt được xử lý bằng công nghệ SIL-TEC trên tấm ngoài và con lăn, tấm bên trong mạ crom Tương thích với hệ thống truyền động 12 tốc độ',
                'created_at' => now(),
                'updated_at' => now(),
            ],


        ]);
    }
}
