<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImgProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('img_products')->insert([
            [
                'id_product' => 1,
                'img_products' => '/img/product/xe-dap-duong-pho2.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'img_products' => '/img/product/xe-dap-duong-pho3.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'img_products' => '/img/product/m-1-06293.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_product' => 1,
                'img_products' => '/img/product/m-1-06300.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'img_products' => '/img/product/m-1-06301.jpg',
                'sort' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'img_products' => '/img/product/2025-alight-4-disc-asphaltgreen_2.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'img_products' => '/img/product/2025-alight-4-disc-balibricks_2.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'img_products' => '/img/product/m-1-06310_2.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'img_products' => '/img/product/m-1-06313_2.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'img_products' => '/img/product/m-1-06316_2.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'img_products' => '/img/product/2025-roam-3-shellwhite_2.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'img_products' => '/img/product/2025-roam-3-ultranavy_2.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'img_products' => '/img/product/m-1-06337_2.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'img_products' => '/img/product/m-1-06339_2.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'img_products' => '/img/product/m-1-06343_2.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'img_products' => '/img/product/2025-roam-4-black_2.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'img_products' => '/img/product/2025-roam-4-mars-dust.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'img_products' => '/img/product/m-1-06374.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'img_products' => '/img/product/m-1-06376.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'img_products' => '/img/product/m-1-06377.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'img_products' => '/img/product/Free24_Black-1-1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'img_products' => '/img/product/Free24_Blue-1-1.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'img_products' => '/img/product/Free24_GrayOrange.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'img_products' => '/img/product/Free24_Silver.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'img_products' => '/img/product/LX08_Black.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'img_products' => '/img/product/LX08_Grey.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'img_products' => '/img/product/LX08_White.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'img_products' => '/img/product/LX08_XanhCoVit.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'img_products' => '/img/product/2024_Escape1Disc_Sandshell_0.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'img_products' => '/img/product/2024_Escape1Disc_Sandshell_2.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'img_products' => '/img/product/2024_Escape1Disc_SnowDrift_0.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'img_products' => '/img/product/2024_Escape1Disc_SnowDrift_1.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'img_products' => '/img/product/LX66_Pink.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'img_products' => '/img/product/LX66_Purple_1.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'img_products' => '/img/product/LX66_Purple_6.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'img_products' => '/img/product/LX66_XanhNgoc.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'img_products' => '/img/product/LX66_White.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // cmt
            [
                'id_product' => 9,
                'img_products' => '/img/product/2024_FastroadADV1_Carbon_1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'img_products' => '/img/product/2024_FastroadADV1_Carbon_3.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'img_products' => '/img/product/2024_FastroadADV1_Carbon_7.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'img_products' => '/img/product/2024_FastroadADV1_Carbon_12.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'img_products' => '/img/product/2024_FastroadADV1_Carbon.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'img_products' => '/img/product/2024_Alight3DDDisc_GoodGray_4.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'img_products' => '/img/product/2024_Alight3DDDisc_GoodGray_5.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'img_products' => '/img/product/2024_Alight3DDDisc_GoodGray_8.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'img_products' => '/img/product/2024_Alight3DDDisc_GoodGray_9.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'img_products' => '/img/product/2024_Alight3DDDisc_GoodGray.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'img_products' => '/img/product/2024_Fastroad1_SeaSparkle_2.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'img_products' => '/img/product/2024_Fastroad1_SeaSparkle_6.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'img_products' => '/img/product/2024_Fastroad1_SeaSparkle_7.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'img_products' => '/img/product/2024_Fastroad1_SeaSparkle_11.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 11,
                'img_products' => '/img/product/2024_Fastroad1_SeaSparkle.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'img_products' => '/img/product/2024_Fastroad2_Charcoal_6.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'img_products' => '/img/product/2024_Fastroad2_Charcoal_11.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'img_products' => '/img/product/2024_Fastroad2_Charcoal_New_2.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'img_products' => '/img/product/2024_Fastroad2_Charcoal_New_5.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'img_products' => '/img/product/2024_Fastroad2_Charcoal_New.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'img_products' => '/img/product/2024_FastroadADV2_HeliosOrange_2.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'img_products' => '/img/product/2024_FastroadADV2_HeliosOrange_3.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'img_products' => '/img/product/2024_FastroadADV2_HeliosOrange_7.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'img_products' => '/img/product/2024_FastroadADV2_HeliosOrange_11.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'img_products' => '/img/product/2024_FastroadADV2_HeliosOrange.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'img_products' => '/img/product/Alpha_Grey_2.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'img_products' => '/img/product/Alpha_White_1.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'img_products' => '/img/product/Alpha_White_10.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'img_products' => '/img/product/Alpha_White.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'img_products' => '/img/product/Totem_Alpha_Grey.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'img_products' => '/img/product/2025-talon-293-frostsilver_2.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'img_products' => '/img/product/m-1-06220.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'img_products' => '/img/product/m-1-06222.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'img_products' => '/img/product/m-1-06224.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'img_products' => '/img/product/m-1-06234.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'img_products' => '/img/product/2025-atx-610-glossblack_2.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'img_products' => '/img/product/2025-atx-610-glossblack-1.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'img_products' => '/img/product/2025-atx-610-latte_2.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'img_products' => '/img/product/2025-atx-610-latte-1.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'img_products' => '/img/product/m-1-02478.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'img_products' => '/img/product/2024_XTCADV2915_Aerospace-BlueCarbon-2.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'img_products' => '/img/product/XTC_ADV3_Red.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'img_products' => '/img/product/xtc-advanced-3-2022-27-5-black-gray-2.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'img_products' => '/img/product/2-1.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'img_products' => '/img/product/5-1.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'img_products' => '/img/product/11-1.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'img_products' => '/img/product/2025-roam-4-black_2.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'img_products' => '/img/product/2025-roam-4-mars-dust.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'img_products' => '/img/product/5-8.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'img_products' => '/img/product/2024_XTCADV292_Black_ShellWhite_0.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'img_products' => '/img/product/2024_XTCADV292_Black_ShellWhite_1.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'img_products' => '/img/product/2024_XTCADV292_Black_ShellWhite_2.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'img_products' => '/img/product/2024_XTCADV292_Black_ShellWhite_5.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'img_products' => '/img/product/2024_XTCADV292_Black_ShellWhite.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'img_products' => '/img/product/PROPEL-ADVANCED-SL-DISC-1-2022.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'img_products' => '/img/product/2025_PropelADV1_BlueDragonfly_1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'img_products' => '/img/product/2025_PropelADV1_BlueDragonfly.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'img_products' => '/img/product/2025_PropelADV1_IllusionWhite.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'img_products' => '/img/product/2025_EnviLivAdvanced1_MechanicRose.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'img_products' => '/img/product/2024_PropelADVP0_MetallicBlueCarbon_2-1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'img_products' => '/img/product/2024_PropelADVP0_MetallicBlueCarbon-1.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'img_products' => '/img/product/2024_PropelADVP0_Sangria_1-1.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'img_products' => '/img/product/2024_PropelADVP0_Sangria_2-1.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'img_products' => '/img/product/2024_PropelADVP0_Sangria-1.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'img_products' => '/img/product/2024_TCRADVP0D-Di2_BlueDragonfly_1-1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'img_products' => '/img/product/2024_TCRADVP0D-Di2_BlueDragonfly_3-1.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'img_products' => '/img/product/2024_TCRADVP0D-Di2_BlueDragonfly_6-1.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'img_products' => '/img/product/2024_TCRADVP0D-Di2_BlueDragonfly_7-1.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'img_products' => '/img/product/2024_TCRADVP0D-Di2_Carbon-1.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'img_products' => '/img/product/2025-contend-1-metallicblack_2.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'img_products' => '/img/product/2025-contend-1-unicornwhite_2.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'img_products' => '/img/product/dm-20241111101103-001.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'img_products' => '/img/product/dm-20241111101103-002.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'img_products' => '/img/product/dm-20241111101103-004.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'img_products' => '/img/product/dm-20241111101103-005.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'img_products' => '/img/product/dm-20241111101103-006.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'img_products' => '/img/product/alight-3-dd-disc-figuier-1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'img_products' => '/img/product/alight-3-dd-disc-figuier-2.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'img_products' => '/img/product/alight-3-dd-disc-figuier-3.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'img_products' => '/img/product/alight-3-dd-disc-figuier-2022-850.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'img_products' => '/img/product/alight-3-dd-disc-pistachio-2022-850.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'img_products' => '/img/product/Trinx_Princess18_1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'img_products' => '/img/product/Trinx_Princess18_2.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'img_products' => '/img/product/Trinx_Princess18_3.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'img_products' => '/img/product/Trinx_Princess18_6.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'img_products' => '/img/product/Trinx_Princess18.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'img_products' => '/img/product/fd-806-blue-fix-1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'img_products' => '/img/product/fd-806-white-fixed-1.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'img_products' => '/img/product/1.7.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'img_products' => '/img/product/2-1 (1).jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'img_products' => '/img/product/3.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 31,
                'img_products' => '/img/product/530000009-850.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 32,
                'img_products' => '/img/product/970845-850.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 33,
                'img_products' => '/img/product/giant-numen-combo-4-black.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 33,
                'img_products' => '/img/product/giant-numen-combo-4-white.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 34,
                'img_products' => '/img/product/610000044-fix.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [

                'id_product' => 35,
                'img_products' => '/img/product/490000011-850.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 36,
                'img_products' => '/img/product/400000194-850-1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 36,
                'img_products' => '/img/product/490000011-850.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 37,
                'img_products' => '/img/product/TY573-850-1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 38,
                'img_products' => '/img/product/VB3887604-1-1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 39,
                'img_products' => '/img/product/ICNHG90111116Q_1.jpeg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 39,
                'img_products' => '/img/product/ICNHG90111116Q_2.jpeg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 39,
                'img_products' => '/img/product/ICNHG90111116Q.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 40,
                'img_products' => '/img/product/ICNLG500126Q_1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 40,
                'img_products' => '/img/product/ICNLG500126Q.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 40,
                'img_products' => '/img/product/CN-LG500.jpeg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'img_products' => '/img/product/EPDM8100_2.jpeg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'img_products' => '/img/product/EPDM8100_2.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'img_products' => '/img/product/EPDM8100_3.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'img_products' => '/img/product/EPDM8100_4.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'img_products' => '/img/product/EPDM8100.jpeg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'img_products' => '/img/product/EPDT8000_1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'img_products' => '/img/product/EPDT8000_2.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'img_products' => '/img/product/EPDT8000_3.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'img_products' => '/img/product/EPDT8000_4.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'img_products' => '/img/product/EPDT8000.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 43,
                'img_products' => '/img/product/350000255-850.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 44,
                'img_products' => '/img/product/350000238-850.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 45,
                'img_products' => '/img/product/340000221-850-1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 46,
                'img_products' => '/img/product/330000094-850-2-1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 47,
                'img_products' => '/img/product/180000365-366-1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 47,
                'img_products' => '/img/product/180000365-366-2.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 47,
                'img_products' => '/img/product/180000365-366-3.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 47,
                'img_products' => '/img/product/180000365-366-4.jpg',
                'sort' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 47,
                'img_products' => '/img/product/180000365-366.jpg',
                'sort' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 48,
                'img_products' => '/img/product/170000278-1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 48,
                'img_products' => '/img/product/170000278-2.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 48,
                'img_products' => '/img/product/170000278.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 49,
                'img_products' => '/img/product/170000269-275_1.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 49,
                'img_products' => '/img/product/170000269-275_2.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 49,
                'img_products' => '/img/product/170000269-275.jpg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 50,
                'img_products' => '/img/product/ICNM8100126Q.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 50,
                'img_products' => '/img/product/ICNM8100.jpg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 50,
                'img_products' => '/img/product/CN-M8100.jpeg',
                'sort' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 51,
                'img_products' => '/img/product/ICNM9100116Q.jpg',
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 51,
                'img_products' => '/img/product/ICNM9100.jpeg',
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
