<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductCustomerSegmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('product_customer_segments')->insert([
            [
                'id' => 1,
                'id_product' => 1,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'id_product' => 1,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'id_product' => 2,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'id_product' => 2,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'id_product' => 3,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'id_product' => 3,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'id_product' => 4,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'id_product' => 4,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'id_product' => 5,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'id_product' => 5,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'id_product' => 6,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'id_product' => 6,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'id_product' => 7,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'id_product' => 7,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'id_product' => 8,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'id_product' => 8,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // cmt
            [
                'id' => 17,
                'id_product' => 9,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'id_product' => 9,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'id_product' => 10,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'id_product' => 10,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'id_product' => 11,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'id_product' => 11,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'id_product' => 12,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'id_product' => 12,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'id_product' => 13,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'id_product' => 13,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'id_product' => 14,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'id_product' => 14,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'id_product' => 15,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'id_product' => 15,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'id_product' => 16,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'id_product' => 16,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'id_product' => 17,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'id_product' => 17,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'id_product' => 18,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'id_product' => 18,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'id_product' => 19,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'id_product' => 19,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'id_product' => 20,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'id_product' => 20,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'id_product' => 21,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'id_product' => 21,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'id_product' => 22,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'id_product' => 22,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'id_product' => 23,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'id_product' => 23,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'id_product' => 24,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'id_product' => 24,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'id_product' => 25,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'id_product' => 25,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'id_product' => 26,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'id_product' => 26,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'id_product' => 27,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'id_product' => 27,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'id_product' => 28,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'id_product' => 28,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'id_product' => 29,
                "id_customer_segment" => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'id_product' => 29,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'id_product' => 30,
                "id_customer_segment" => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'id_product' => 30,
                "id_customer_segment" => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'id_product' => 31,
                "id_customer_segment" => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'id_product' => 31,
                "id_customer_segment" => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
