<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductVariantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('product_variants')->insert([
            [
                'id' => 1,
                'id_product' => 1,
                'option' => 'Pale Olive',
                'price' => 11290000,
                'image' => '/img/product/2025-alight-3-liv-tt-1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 2,
                'id_product' => 2,
                'option' => 'Asphalt Green',
                'price' => 10790000,
                'image' => '/img/product/2025-alight-4-disc-asphaltgreen_2.jpg',
                'stock' => 10,
            ],
            [
                'id' => 3,
                'id_product' => 2,
                'option' => 'Bali Bricks',
                'price' => 11290000,
                'image' => '/img/product/2025-alight-4-disc-balibricks_2.jpg',
                'stock' => 10,
            ],
            [
                'id' => 4,
                'id_product' => 3,
                'option' => 'Shell White',
                'price' => 14790000,
                'image' => '/img/product/2025-roam-3-shellwhite_3.jpg',
                'stock' => 10,
            ],
            [
                'id' => 5,
                'id_product' => 3,
                'option' => 'Ultra Navy',
                'price' => 14590000,
                'image' => '/img/product/2025-roam-3-ultranavy_3.jpg',
                'stock' => 10,
            ],
            [
                'id' => 6,
                'id_product' => 4,
                'option' => 'Black Dust',
                'price' => 12790000,
                'image' => '/img/product/2025-roam-4-black_2.jpg',
                'stock' => 10,
            ],
            [
                'id' => 7,
                'id_product' => 4,
                'option' => 'Mars Dust',
                'price' => 12590000,
                'image' => '/img/product/2025-roam-4-mars-dust.jpg',
                'stock' => 10,
            ],
            [
                'id' => 8,
                'id_product' => 5,
                'option' => 'Sliver GB',
                'price' => 6990000,
                'image' => '/img/product/Free24_Silver.jpg',
                'stock' => 20,
            ],
            [
                'id' => 9,
                'id_product' => 5,
                'option' => 'Blue BG',
                'price' => 6590000,
                'image' => '/img/product/Free24_Blue-1-1.jpg',
                'stock' => 0,
            ],
            [
                'id' => 10,
                'id_product' => 5,
                'option' => 'Black RW',
                'price' => 6790000,
                'image' => '/img/product/Free24_Black-1-1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 11,
                'id_product' => 6,
                'option' => 'Green CV',
                'price' => 8390000,
                'image' => '/img/product/LX08_XanhCoVit.jpg',
                'stock' => 5,
            ],
            [
                'id' => 12,
                'id_product' => 6,
                'option' => 'Black JEEP',
                'price' => 9590000,
                'image' => '/img/product/LX08_Black.jpg',
                'stock' => 12,
            ],
            [
                'id' => 13,
                'id_product' => 6,
                'option' => 'Grep JEEP',
                'price' => 9290000,
                'image' => '/img/product/LX08_Grey.jpg',
                'stock' => 20,
            ],
            [
                'id' => 14,
                'id_product' => 6,
                'option' => 'White JEEP',
                'price' => 9990000,
                'image' => '/img/product/LX08_White.jpg',
                'stock' => 40,
            ],
            [
                'id' => 15,
                'id_product' => 7,
                'option' => 'Snow Drift',
                'price' => 17990000,
                'image' => '/img/product/2024_Escape1Disc_SnowDrift_0.jpg',
                'stock' => 0,
            ],
            [
                'id' => 16,
                'id_product' => 7,
                'option' => 'Sandshell',
                'price' => 17790000,
                'image' => '/img/product/2024_Escape1Disc_Sandshell_0.jpg',
                'stock' => 10,
            ],
            [
                'id' => 17,
                'id_product' => 8,
                'option' => 'Green',
                'price' => 6790000,
                'image' => '/img/product/LX66_XanhNgoc.jpg',
                'stock' => 0,
            ],
            [
                'id' => 18,
                'id_product' => 8,
                'option' => 'Pink',
                'price' => 6690000,
                'image' => '/img/product/LX66_Pink.jpg',
                'stock' => 5,
            ],
            [
                'id' => 19,
                'id_product' => 8,
                'option' => 'Purple',
                'price' => 6590000,
                'image' => '/img/product/LX66_Purple_1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 20,
                'id_product' => 8,
                'option' => 'White',
                'price' => 6890000,
                'image' => '/img/product/LX66_White.jpg',
                'stock' => 20,
            ],
            [
                'id' => 21,
                'id_product' => 8,
                'option' => 'Black',
                'price' => 6600000,
                'image' => '/img/product/LX66_Black.jpg',
                'stock' => 20,
            ],
            [
                'id' => 22,
                'id_product' => 9,
                'option' => 'Black',
                'price' => 48790000,
                'image' => '/img/product/2024_FastroadADV1_Carbon.jpg',
                'stock' => 10,
            ],
            [
                'id' => 23,
                'id_product' => 10,
                'option' => 'Good Gray',
                'price' => 11390000,
                'image' => '/img/product/2024_Alight3DDDisc_GoodGray.jpg',
                'stock' => 10,
            ],
            [
                'id' => 24,
                'id_product' => 11,
                'option' => 'Sea Sparkle',
                'price' => 26990000,
                'image' => '/img/product/2024_Fastroad1_SeaSparkle.jpg',
                'stock' => 10,
            ],
            [
                'id' => 25,
                'id_product' => 12,
                'option' => 'Charcoal',
                'price' => 23490000,
                'image' => '/img/product/2024_Fastroad2_Charcoal_New.jpg',
                'stock' => 5,
            ],
            [
                'id' => 26,
                'id_product' => 13,
                'option' => 'Helios Orange',
                'price' => 39490000,
                'image' => '/img/product/2024_FastroadADV2_HeliosOrange.jpg',
                'stock' => 5,
            ],
            [
                'id' => 27,
                'id_product' => 14,
                'option' => 'Black Blue',
                'price' => 8490000,
                'image' => '/img/product/Totem_Alpha_Grey.jpg',
                'stock' => 5,
            ],
            [
                'id' => 28,
                'id_product' => 14,
                'option' => 'White Blue',
                'price' => 8590000,
                'image' => '/img/product/Alpha_White.jpg',
                'stock' => 5,
            ],
            [
                'id' => 29,
                'id_product' => 15,
                'option' => 'Frost Silver',
                'price' => 13990000,
                'image' => '/img/product/2025-talon-293-frostsilver_2.jpg',
                'stock' => 10,
            ],
            [
                'id' => 30,
                'id_product' => 16,
                'option' => 'Latte',
                'price' => 8290000,
                'image' => '/img/product/2025-atx-610-latte_2.jpg',
                'stock' => 10,
            ],
            [
                'id' => 31,
                'id_product' => 16,
                'option' => 'Gloss Black',
                'price' => 8190000,
                'image' => '/img/product/2025-atx-610-glossblack_2.jpg',
                'stock' => 10,
            ],
            [
                'id' => 32,
                'id_product' => 17,
                'option' => 'Aerospace Blue',
                'price' => 76990000,
                'image' => '/img/product/2024_XTCADV2915_Aerospace-BlueCarbon-2.jpg',
                'stock' => 10,
            ],
            [
                'id' => 33,
                'id_product' => 18,
                'option' => 'Pure Red',
                'price' => 46990000,
                'image' => '/img/product/XTC_ADV3_Red.jpg',
                'stock' => 10,
            ],
            [
                'id' => 34,
                'id_product' => 18,
                'option' => 'Black Gray',
                'price' => 46790000,
                'image' => '/img/product/14-1-e1672721275973.jpg',
                'stock' => 10,
            ],
            [
                'id' => 35,
                'id_product' => 19,
                'option' => 'Sapphire',
                'price' => 12290000,
                'image' => '/img/product/roam-4-disc-2022-sapphire.jpg',
                'stock' => 10,
            ],
            [
                'id' => 36,
                'id_product' => 19,
                'option' => 'Black',
                'price' => 12490000,
                'image' => '/img/product/roam-4-disc-2022-black.jpg',
                'stock' => 10,
            ],
            [
                'id' => 37,
                'id_product' => 20,
                'option' => 'Black White',
                'price' => 59990000,
                'image' => '/img/product/2024_XTCADV292_Black_ShellWhite_0.jpg',
                'stock' => 10,
            ],
            // 
            // 
            // 
            [
                'id' => 38,
                'id_product' => 21,
                'option' => 'Black Diamond',
                'price' => 117690000,
                'image' => '/img/product/PROPEL-ADVANCED-SL-DISC-1-2022.jpg',
                'stock' => 10,
            ],
            [
                'id' => 39,
                'id_product' => 22,
                'option' => 'Blue Dragonfly',
                'price' => 92390000,
                'image' => '/img/product/2025_PropelADV1_BlueDragonfly.jpg',
                'stock' => 10,
            ],
            [
                'id' => 40,
                'id_product' => 22,
                'option' => 'LIIsion White',
                'price' => 92490000,
                'image' => '/img/product/2025_PropelADV1_BlueDragonfly_1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 41,
                'id_product' => 23,
                'option' => 'Mechanic Rose',
                'price' => 101190000,
                'image' => '/img/product/2025_EnviLivAdvanced1_MechanicRose.jpg',
                'stock' => 10,
            ],
            [
                'id' => 42,
                'id_product' => 24,
                'option' => 'Metallic Blue',
                'price' => 135290000,
                'image' => '/img/product/2024_PropelADVP0_MetallicBlueCarbon-1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 43,
                'id_product' => 24,
                'option' => 'Sangria',
                'price' => 134390000,
                'image' => '/img/product/2024_PropelADVP0_Sangria-1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 44,
                'id_product' => 25,
                'option' => 'Blue DragonFly',
                'price' => 114390000,
                'image' => '/img/product/2024_TCRADVP0D-Di2_BlueDragonfly-1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 45,
                'id_product' => 25,
                'option' => 'Black Dragonfly',
                'price' => 113390000,
                'image' => '/img/product/2024_TCRADVP0D-Di2_Carbon-1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 46,
                'id_product' => 26,
                'option' => 'Metallic Black',
                'price' => 21790000,
                'image' => '/img/product/2025-contend-1-metallicblack_2.jpg',
                'stock' => 10,
            ],
            [
                'id' => 47,
                'id_product' => 26,
                'option' => 'Unicorn White',
                'price' => 21590000,
                'image' => '/img/product/2025-contend-1-unicornwhite_2.jpg',
                'stock' => 10,
            ],
            [
                'id' => 48,
                'id_product' => 27,
                'option' => 'Eucalyptus',
                'price' => 21590000,
                'image' => '/img/product/dm-20241111101103-001.jpg',
                'stock' => 10,
            ],
            [
                'id' => 49,
                'id_product' => 28,
                'option' => 'Pistachio',
                'price' => 11390000,
                'image' => '/img/product/alight-3-dd-disc-pistachio-2022-850.jpg',
                'stock' => 10,
            ],
            [
                'id' => 50,
                'id_product' => 28,
                'option' => 'Figuier',
                'price' => 11490000,
                'image' => '/img/product/alight-3-dd-disc-figuier-2022-850.jpg',
                'stock' => 10,
            ],
            [
                'id' => 51,
                'id_product' => 29,
                'option' => 'Pink White',
                'price' => 1990000,
                'image' => '/img/product/Trinx_Princess18.jpg',
                'stock' => 10,
            ],
            [
                'id' => 52,
                'id_product' => 30,
                'option' => 'Metallic Blue',
                'price' => 8790000,
                'image' => '/img/product/fd-806-blue-fix-1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 53,
                'id_product' => 30,
                'option' => 'Pearl White',
                'price' => 8690000,
                'image' => '/img/product/fd-806-white-fixed-1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 54,
                'id_product' => 30,
                'option' => 'Metallic Black',
                'price' => 8890000,
                'image' => '/img/product/1.7.jpg',
                'stock' => 10,
            ],
            [
                'id' => 55,
                'id_product' => 31,
                'option' => 'Black',
                'price' => 349000,
                'image' => '/img/product/530000009-850.jpg',
                'stock' => 20,
            ],
            [
                'id' => 56,
                'id_product' => 32,
                'option' => 'Black',
                'price' => 590000,
                'image' => '/img/product/970845-850.jpg',
                'stock' => 10,
            ],
            [
                'id' => 57,
                'id_product' => 33,
                'option' => 'Black',
                'price' => 480000,
                'image' => '/img/product/giant-numen-combo-4-black.jpg',
                'stock' => 10,
            ],
            [
                'id' => 58,
                'id_product' => 33,
                'option' => 'White',
                'price' => 499000,
                'image' => '/img/product/giant-numen-combo-4-white.jpg',
                'stock' => 10,
            ],
            [
                'id' => 59,
                'id_product' => 34,
                'option' => '160g',
                'price' => 659000,
                'image' => '/img/product/610000044-fix.jpg',
                'stock' => 10,
            ],
            [
                'id' => 60,
                'id_product' => 35,
                'option' => 'Matte Black',
                'price' => 659000,
                'image' => '/img/product/490000011-850.jpg',
                'stock' => 10,
            ],
            [
                'id' => 61,
                'id_product' => 35,
                'option' => 'Matte Red',
                'price' => 659000,
                'image' => '/img/product/490000013-850.jpg',
                'stock' => 10,
            ],
            [
                'id' => 62,
                'id_product' => 36,
                'option' => 'Balck',
                'price' => 119000,
                'image' => '/img/product/400000194-850-1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 63,
                'id_product' => 37,
                'option' => 'Balck',
                'price' => 369000,
                'image' => '/img/product/khoa-ty02-Black.jpg',
                'stock' => 10,
            ],
            [
                'id' => 64,
                'id_product' => 38,
                'option' => 'Balck',
                'price' => 369000,
                'image' => '/img/product/day-khoa-vinbike-Black.jpg',
                'stock' => 10,
            ],
            [
                'id' => 65,
                'id_product' => 39,
                'option' => 'Sliver',
                'price' => 1490000,
                'image' => '/img/product/sen-shimano-sliver.jpg',
                'stock' => 10,
            ],
            [
                'id' => 66,
                'id_product' => 40,
                'option' => 'Sliver',
                'price' => 549000,
                'image' => '/img/product/2025-sen-shimano-sliver-1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 67,
                'id_product' => 41,
                'option' => 'Black',
                'price' => 2390000,
                'image' => '/img/product/2025-ban-dap-shimano-Black-epd.jpeg',
                'stock' => 10,
            ],
            [
                'id' => 68,
                'id_product' => 42,
                'option' => 'Black',
                'price' => 2149000,
                'image' => '/img/product/2025-pedal-shimano-t8000-Black.jpg',
                'stock' => 10,
            ],
            [
                'id' => 69,
                'id_product' => 43,
                'option' => 'Black',
                'price' => 20990000,
                'image' => '/img/product/2025-banh-xe-dap-sau-giant-srl-black-1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 70,
                'id_product' => 44,
                'option' => 'Black',
                'price' => 17990000,
                'image' => '/img/product/2025-banh-xe-dap-truoc-giant-2.jpg',
                'stock' => 10,
            ],
            [
                'id' => 71,
                'id_product' => 45,
                'option' => 'Black',
                'price' => 690000,
                'image' => '/img/product/2025-vo-xe-dap-khong-ruot-giant-crosscut-1.jpg',
                'stock' => 10,
            ],
            [
                'id' => 72,
                'id_product' => 46,
                'option' => 'Black',
                'price' => 139000,
                'image' => '/img/product/2025-ruot-xe-dap-giant-Black.jpg',
                'stock' => 10,
            ],
            [
                'id' => 73,
                'id_product' => 47,
                'option' => 'Black',
                'price' => 7590000,
                'image' => '/img/product/2025-ghi-dong-xe-dap-400mm-giant-aero-handlebar-black.jpg',
                'stock' => 10,
            ],
            [
                'id' => 74,
                'id_product' => 48,
                'option' => 'Black',
                'price' => 7490000,
                'image' => '/img/product/2025-po-tang-xe-dap-giant-aero-Black.jpg',
                'stock' => 10,
            ],
            [
                'id' => 75,
                'id_product' => 49,
                'option' => 'Black 100mm',
                'price' => 3590000,
                'image' => '/img/product/2025-po-tang-xe-dap-nhom-giant-Black100mm.jpg',
                'stock' => 10,
            ],
            [
                'id' => 76,
                'id_product' => 50,
                'option' => 'Silver',
                'price' => 999000,
                'image' => '/img/product/2025-sen-shimano-hg-12-m8100-silver.jpg',
                'stock' => 10,
            ],
            [
                'id' => 77,
                'id_product' => 51,
                'option' => 'Silver',
                'price' => 1299000,
                'image' => '/img/product/2025-xich-xe-dap-shimano-cn-m9100-silver.jpg',
                'stock' => 10,
            ],
        ]);
    }
}
