<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sub_categories')->insert([
            [
                "id_main_category" => 1,
                'name' => 'xe đạp thể thao',
                'image' => '/img/category/xe-dap-dua-4.png',
                'slug' => 'xe-dap-the-thao-1',
                'status' => 1,
                'sort' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'xe đạp đường trường',
                'image' => '/img/category/catexeduongtruong-2.png',
                'slug' => 'xe-dap-duong-truong-2',
                'status' => 1,
                'sort' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'xe đạp địa hình',
                'image' => '/img/category/dia-hinh-3.png',
                'slug' => 'xe-dap-dia-hinh-3',
                'sort' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'xe đạp đua',
                'image' => '/img/category/xe-dap-duong-truong-25.png',
                'slug' => 'xe-dap-dua-4',
                'sort' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'xe đạp gấp',
                'image' => '/img/category/xedap-gap-5.png',
                'slug' => 'xe-dap-gap-5',
                'sort' => 5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'xe đạp phổ thông ',
                'image' => '/img/category/xe-dap-pho-thong-6.png',
                'slug' => 'xe-dap-pho-thong-6',
                'sort' => 6,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'xe đạp học sinh',
                'image' => '/img/category/xe-dap-hoc-sinh-7.png',
                'slug' => 'xe-dap-hoc-sinh-7',
                'sort' => 7,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'xe đạp carbon ',
                'image' => '/img/category/xe-dap-duong-truong-25.png',
                'slug' => 'xe-dap-carbon-8',
                'sort' => 8,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'xe đạp nữ',
                'image' => '/img/category/xe-dap-nu-8.png',
                'slug' => 'xe-dap-nu-9',
                'sort' => 9,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'xe đạp trẻ em',
                'image' => '/img/category/xe-dap-tre-em.png',
                'slug' => 'xe-dap-tre-em-10',
                'sort' => 10,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'xe đạp điện',
                'image' => '/img/category/imagexe-dap-dien.png',
                'slug' => 'xe-dap-dien-11',
                'sort' => 11,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'xe đạp fixed gear',
                'image' => '/img/category/xe-dap-duong-truong-25.png',
                'slug' => 'xe-dap-fixed-gear-12',
                'sort' => 12,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'xe đạp trợ lực',
                'image' => '/img/category/xe-tro-luc.png',
                'slug' => 'xe-dap-tro-luc-13',
                'sort' => 13,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 1,
                'name' => 'Xe đạp Hybird',
                'image' => '/img/category/xe-dap-duong-truong-25.png',
                'slug' => 'xe-dap-hybrid-14',
                'sort' => 14,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 2,
                'name' => 'Phụ kiện',
                'image' => '/img/category/phu-kien-aa.png',
                'slug' => 'phu-kien-xe-dap-15',
                'sort' => 1000,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 2,
                'name' => 'Baga - Chắn bùn',
                'image' => '/img/category/phu-kien-aa.png',
                'slug' => 'phu-kien-baga-chan-bun-16',
                'sort' => 1001,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 2,
                'name' => 'Gọng nước - Bình nước',
                'image' => '/img/category/phu-kien-aa.png',
                'slug' => 'phu-kien-gong-nuoc-binh-nuoc-17',
                'sort' => 1002,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 2,
                'name' => 'Ống bơm - Phụ kiện bơm',
                'image' => '/img/category/phu-kien-aa.png',
                'slug' => 'phu-kien-bom-ong-bom-18',
                'sort' => 1003,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 2,
                'name' => 'Đèn',
                'image' => '/img/category/phu-kien-aa.png',
                'slug' => 'phu-kien-den-19',
                'sort' => 1004,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 2,
                'name' => 'Khóa',
                'image' => '/img/category/phu-kien-aa.png',
                'slug' => 'phu-kien-khoa-20',
                'sort' => 1005,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            // phu tung
            [
                "id_main_category" => 3,
                'name' => 'Sên',
                'image' => '/img/category/phu-kien-aa.png',
                'slug' => 'phu-tung-sen-21',
                'sort' => 1006,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 3,
                'name' => 'Bàn đạp',
                'image' => '/img/category/phu-kien-aa.png',
                'slug' => 'phu-tung-ban-dap-22',
                'sort' => 1007,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 3,
                'name' => 'Bánh - Niềng Xe',
                'image' => '/img/category/phu-kien-aa.png',
                'slug' => 'phu-tung-banh-nien-xe-23',
                'sort' => 1008,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 3,
                'name' => 'Vỏ - Ruột Xe',
                'image' => '/img/category/phu-kien-aa.png',
                'slug' => 'phu-tung-vo-ruot-xe-24',
                'sort' => 1009,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id_main_category" => 3,
                'name' => 'Ghi đông - Pô tăng',
                'image' => '/img/category/phu-kien-aa.png',
                'slug' => 'phu-tung-ghi-dong-po-tang-25',
                'sort' => 1010,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
